#!/bin/bash

# print the header (the first line of input) 
# and then run the specified command on the body (the rest of the input) 
# use it in a pipeline, e.g. ps | body grep somepattern 
body() {
    IFS= read -r head er     
    printf '%s\n' "$header"     
    "$@" 
}

hugefile(){
    find -type f -exec du -Sh {} + | sort -rh | head -n "$1"
}

hugefolder(){
    du -Sh ./ | sort -rh | head -n "$1";
}

foldersize(){
    for each in $(ls -a) ; 
        do du -hs "$each" ; 
    done
}

dockerpush(){
    docker tag "$1" "localhost:5000/$1";
    docker push "localhost:5000/$1";
    docker rmi "localhost:5000/$1";
}

#rmhugefile(){
#    rm -ri $(hugefile $1 | awk '{print $NF}' | grep $2)
#}

#rmhugefolder(){
#    rm -ri $(hugefolder $1 | awk '{print $NF}' | grep $2)
#}

# runlike https://github.com/lavie/runlike
